emojipack:
  basic:
    grin:
      emoticon: ':grin:'
      emoji: '&f'
    beaming:
      emoticon: ':beaming:'
      emoji: '&f'
    smile:
      emoticon: ':smile:'
      emoji: '&f'
    ill:
      emoticon: ':ill:'
      emoji: '&f'
    devil_smile:
      emoticon: ':devil_smile:'
      emoji: '&f'
    facemask:
      emoticon: ':facemask:'
      emoji: '&f'
    wink:
      emoticon: ':wink:'
      emoji: '&f'
    wink_grin:
      emoticon: ':wink_grin:'
      emoji: '&f'
    tongue_smile:
      emoticon: ':tongue_smile:'
      emoji: '&f'
    hot:
      emoticon: ':hot:'
      emoji: '&f'
    devil_sad:
      emoticon: ':devil_sad:'
      emoji: '&f'
    heart_eyes:
      emoticon: ':heart_eyes:'
      emoji: '&f'
    sweat_smile:
      emoticon: ':sweat_smile:'
      emoji: '&f'
    eyes:
      emoticon: ':eyes:'
      emoji: '&f'
    cool_dude:
      emoticon: ':cool_dude:'
      emoji: '&f'
    angry:
      emoticon: ':angry:'
      emoji: '&f'
    poop:
      emoticon: ':poop:'
      emoji: '&f'
    k:
      emoticon: ':k:'
      emoji: '&f'
    sad:
      emoticon: ':sad:'
      emoji: '&f'
    cry:
      emoticon: ':cry:'
      emoji: '&f'     
    tongue_squint:
      emoticon: ':tongue_squint:'
      emoji: '&f'
    drool:
      emoticon: ':drool:'
      emoji: '&f'
    tear_flood:
      emoticon: ':tear_flood:'
      emoji: '&f'
    wink_tongue:
      emoticon: ':wink_tongue:'
      emoji: '&f'
    omg:
      emoticon: ':omg:'
      emoji: '&f'
    shocked:
      emoticon: ':shocked:'
      emoji: '&f'
    vile:
      emoticon: ':vile:'
      emoji: '&f'
    clown:
      emoticon: ':clown:'
      emoji: '&f'
    thumbs_up:
      emoticon: ':thumbs_up:'
      emoji: '&f'
    thumbs_down:
      emoticon: ':thumbs_down:'
      emoji: '&f'
    mind_blown:
      emoticon: ':mind_blown:'
      emoji: '&f'
    cold:
      emoticon: ':cold:'
      emoji: '&f'
    angel:
      emoticon: ':angel:'
      emoji: '&f'
    wow:
      emoticon: ':wow:'
      emoji: '&f'
    zipped:
      emoticon: ':zipped:'
      emoji: '&f'
    red_heart:
      emoticon: ':red_heart:'
      emoji: '&f'
    yellow_heart:
      emoticon: ':yellow_heart:'
      emoji: '&f'
    purple_heart:
      emoticon: ':purple_heart:'
      emoji: '&f'
    green_heart:
      emoticon: ':green_heart:'
      emoji: '&f'
    upside_down:
      emoticon: ':upside_down:'
      emoji: '&f'
    tired:
      emoticon: ':tired:'
      emoji: '&f'
    skull:
      emoticon: ':skull:'
      emoji: '&f'
    yellow_skull:
      emoticon: ':yellow_skull:'
      emoji: '&f'     
    cowboy:
      emoticon: ':cowboy:'
      emoji: '&f'
    pumpkin_smile:
      emoticon: ':pumpkin_smile:'
      emoji: '&f'
    broken_heart:
      emoticon: ':broken_heart:'
      emoji: '&f'
#  premium:
#    example:
#      emoticon: ':example:'
#      emoji: '&f'

#permission for premium = chatemojis.use.emojipack.premium.<EMOJI_NAME>
#permission for basic = chatemojis.use.emojipack.basic.<EMOJI_NAME>
