name: EmojiPack
version: ${project.version}
main: com.rmjtromp.chatemojis.ChatEmojis
api-version: 1.13
authors: [ RMJTromp, TwistedDreams ]
soft-depend: [ PlaceholderAPI ]

commands:
  emoji:
    usage: <command>
    aliases: emojis
    description: Shows a list of emojis

permissions:
  chatemojis.command:
    description: permission to use list all emojis (deprecated)
    default: false
  chatemojis.list:
    description: permission to use list all emojis
    default: true
  chatemojis.use.*:
    description: permission to use all emojis
    default: op
  chatemojis.reload:
    description: permission to reload emojis
    default: op
  chatemojis.admin:
    description: permission to make changes to settings
    default: op
    children:
      - chatemojis.reload
  chatemojis.*:
    description: permission to list and use all emojis
    default: op
    children:
      - chatemojis.list
      - chatemojis.use.*
      - chatemojis.admin

